// Generated by gencpp from file rc_msgs/calibrateResult.msg
// DO NOT EDIT!


#ifndef RC_MSGS_MESSAGE_CALIBRATERESULT_H
#define RC_MSGS_MESSAGE_CALIBRATERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rc_msgs/point.h>

namespace rc_msgs
{
template <class ContainerAllocator>
struct calibrateResult_
{
  typedef calibrateResult_<ContainerAllocator> Type;

  calibrateResult_()
    : data()  {
    }
  calibrateResult_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rc_msgs::point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rc_msgs::point_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rc_msgs::calibrateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_msgs::calibrateResult_<ContainerAllocator> const> ConstPtr;

}; // struct calibrateResult_

typedef ::rc_msgs::calibrateResult_<std::allocator<void> > calibrateResult;

typedef boost::shared_ptr< ::rc_msgs::calibrateResult > calibrateResultPtr;
typedef boost::shared_ptr< ::rc_msgs::calibrateResult const> calibrateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_msgs::calibrateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_msgs::calibrateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rc_msgs::calibrateResult_<ContainerAllocator1> & lhs, const ::rc_msgs::calibrateResult_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rc_msgs::calibrateResult_<ContainerAllocator1> & lhs, const ::rc_msgs::calibrateResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::calibrateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::calibrateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::calibrateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::calibrateResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::calibrateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::calibrateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_msgs::calibrateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f88ab6e515853fd3715748d3598553b1";
  }

  static const char* value(const ::rc_msgs::calibrateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf88ab6e515853fd3ULL;
  static const uint64_t static_value2 = 0x715748d3598553b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_msgs::calibrateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_msgs/calibrateResult";
  }

  static const char* value(const ::rc_msgs::calibrateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_msgs::calibrateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point[] data\n"
"\n"
"================================================================================\n"
"MSG: rc_msgs/point\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::rc_msgs::calibrateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_msgs::calibrateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_msgs::calibrateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_msgs::calibrateResult_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rc_msgs::point_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_MSGS_MESSAGE_CALIBRATERESULT_H
